// <auto-generated />
using Housing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Housing.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Housing.Data.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            CountryName = "United State",
                            ShortName = "US"
                        },
                        new
                        {
                            CountryId = 2,
                            CountryName = "United Kingdom",
                            ShortName = "UK"
                        },
                        new
                        {
                            CountryId = 3,
                            CountryName = "Australia",
                            ShortName = "AUS"
                        });
                });

            modelBuilder.Entity("Housing.Data.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfRooms")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Houses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "BA 213445 street",
                            CountryId = 1,
                            NumberOfRooms = 4,
                            Size = " 2400x2000x5000",
                            State = "Massachusetts"
                        },
                        new
                        {
                            Id = 2,
                            Address = "AD 093848 paddington",
                            CountryId = 3,
                            NumberOfRooms = 5,
                            Size = " 24000x60000x50000",
                            State = "Adelaide"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Nc 445 street pittsburg",
                            CountryId = 2,
                            NumberOfRooms = 6,
                            Size = " 24000x30000x80000",
                            State = "NewCastle"
                        });
                });

            modelBuilder.Entity("Housing.Data.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Population")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StateCode")
                        .HasColumnType("int");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 2,
                            Population = "23 million",
                            StateCode = 244,
                            StateName = "Newcastle"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 3,
                            Population = "16 million",
                            StateCode = 22280,
                            StateName = "Adelaide"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            Population = "60 million",
                            StateCode = 553,
                            StateName = "Massachusetts"
                        });
                });

            modelBuilder.Entity("Housing.Data.House", b =>
                {
                    b.HasOne("Housing.Data.Country", "Country")
                        .WithMany("Houses")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Housing.Data.State", b =>
                {
                    b.HasOne("Housing.Data.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Housing.Data.Country", b =>
                {
                    b.Navigation("Houses");

                    b.Navigation("States");
                });
#pragma warning restore 612, 618
        }
    }
}
